### ISSUE TITLE
Password protection goes wrong

### ISSUE THREAD

**Issue by gerard33** [mr-bjerre/hassio-remote-backup#1]
Thanks for adding the password protection!

When using the password protection in v0.2.0 something goes wrong.

I have added `"zip_password": "mypassword"` to the config.
Then the backup is made and correctly copied via scp.
But when unpacking the file, I get the message that password is incorrect and I am sure I use the right one ;)
Also after the backup is finished the `"zip_password": "mypassword"` has dissapeared from the config file.

Below the output of the log.
```
starting version 3.2.4
Adding SSH key
Creating local backup: "Automated backup 2018-03-11 01:34"
Backup created: 2e60f3ec
Copying password-protected 2e60f3ec.zip to ~/Onedrive/Backup_Home_Assistant/hassio-snapshot/ on 192.168.1.102 using SCP
  adding: 2e60f3ec.tar (deflated 1%)
Warning: Permanently added '192.168.1.102' (ECDSA) to the list of known hosts.
ok
Deleted local backup: 2e60f3ec
Backup process done!
```

**Comment by khan3962** [comment]
I also see the config item being removed before starting the addon.  Additionally if the option isn't set it still password protects the file.  No idea what the password is, no way to use it.  Officially un-usable.  Loved it before though, please fix!

Edit: Anyone that needs into the zip file the password will be "null" lower case, the actual word not "empty" like the Chinese do it.

**Comment by khan3962** [comment]
I submitted a pull request to your hassio-addons to fix this issue.  Sorry for all the commits, I'm new to this github collaboration thing.  Only thing changed is adding "zip_password": "" to the config.json .

**Comment by NixBiks** [comment]
Thank you very much for pointing it out. This is quite a critical bug for sure.

The `config.json` from the [addons repo](https://github.com/mr-bjerre/hassio-addons) got out of sync which caused it. I've now updated to [v0.2.1](https://github.com/mr-bjerre/hassio-remote-backup/releases/tag/v0.2.1) where it is fixed. As @khan3962 points out; the password is _null_ for all the backups created with [v0.2.0](https://github.com/mr-bjerre/hassio-remote-backup/releases/tag/v0.2.0).
