### ISSUE TITLE
Function to only remove older versions of snapshot from hass.io server

### ISSUE THREAD

**Issue by gerard33** [mr-bjerre/hassio-remote-backup#2]
Is it possible to implement a function so you can keep the lasts x versions of the snapshot on the hass.io server? Now the backup is directly removed after the add-on has run.

See [here](https://github.com/danielwelch/hassio-dropbox-sync/blob/master/dropbox-sync/keep_last.py) for an example where a configurable number of backups will remain on the hass.io server.

**Comment by NixBiks** [comment]
The thing is that this will not only remove the snapshots created by the addon but remove all backups. I guess I'll just make it optional with an input `keep_local_backup` with possible values:

1. `0`: do not keep any backups created by the addon. This does not interfere with any other local backups.
1. `X` with `X > 0`: keep last `X` snapshots. Note this will also delete snapshots not created by the addon.
1. `all`: do not delete any local backups.

**Comment by gerard33** [comment]
Thanks for adding this :+1: 

When I enter `"keep_local_backup": "all"` all is working fine, but when entering `"keep_local_backup": "14"` I get the following error `not a valid value for dictionary value @ data['options'].`.

**Comment by NixBiks** [comment]
Argh. I have a zero or one character allowance instead of zero or more. Try having “9” - does that work?

I am in the middle of moving so I am on smartphone only. It is a fix to my addon repo which I will fix today but it might not go into effect until you install the addon (either reinstall or wait for next upgrade).

**Comment by gerard33** [comment]
Thanks, it's working now correctly!
