### ISSUE TITLE
Add-on Stopped working - Impossible to pull again

### ISSUE THREAD

**Issue by mbrasseur** [mr-bjerre/hassio-remote-backup#21]
Hi,

Having an issue with my HassIO instance, I had to opt for a fresh setup and restore a snapshot.  Following this, Remote-Backup didn't work anymore.  I've uninstalled it and now when trying to pull the image again, home-assistant.log is displaying the following error:

_1_9-03-22 20:12:15 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install fixated/remote-backup-armv7:0.3.2 -> 404 Client Error: Not Found ("pull access denied for fixated/remote-backup-armv7, repository does not exist or may require 'docker login'").__

Any idea?

Thanks for you help and this really great add-on!! ;-)

**Comment by pssc** [comment]
Me to but with a fresh install...

`19-03-26 08:57:34 INFO (SyncWorker_16) [hassio.docker.interface] Pull image fixated/remote-backup-armv7 tag 0.3.2.
19-03-26 08:57:35 ERROR (SyncWorker_16) [hassio.docker.interface] Can't install fixated/remote-backup-armv7:0.3.2 -> 404 Client Error: Not Found ("pull access denied for fixated/remote-backup-armv7, repository does not exist or may require 'docker login'").`

**Comment by mbrasseur** [comment]
Ok, good news, I'm not the only one :) 

Could it be related to something missing on docker side ?

**Comment by ryanmboyce** [comment]
Same error here, sorry for duplicate Issue posted.

**Comment by cbrherms** [comment]
I'm getting something similar. Had to restore addon from backup but causing errors in logs

**Comment by cbrherms** [comment]
missing `"arch"` key from config.json in [hassio-addons repo](https://github.com/mr-bjerre/hassio-addons/blob/master/remote-backup/config.json) and [the addon itself](https://github.com/mr-bjerre/hassio-remote-backup/blob/master/remote-backup/config.json).

Think that might be the issue causing the inability to pull

**Comment by gerard33** [comment]
If this great add-on is not maintained anymore (which would be a pitty) you can have a look at this fork
https://github.com/carstenschroeder/hassio-addons.

**Comment by ryanmboyce** [comment]
> If this great add-on is not maintained anymore (which would be a pitty) you can have a look at this fork
> https://github.com/carstenschroeder/hassio-addons.

@gerard33 Thank you for linking to this fork, it's a no brainer to get these backups of the SSD card. I installed the add-on however getting the following error when starting the docker container running hassio:

**/usr/bin/hassio: line 1: Not: command not found**

Is it possible that "Not:" is referenced somewhere because I have the command hassio installed in /usr/bin/hassio:
**a0d7b954-ssh:~/config# which hassio
/usr/bin/hassio**

Docker logs:
`Adding SSH key
Creating local backup: "Automated backup 2019-04-07 05:55"
/usr/bin/hassio: line 1: Not: command not found
Backup created: 
Copying .tar to /mnt/backupdir/ on **mybackup.remotehost.com** using SCP
Warning: Permanently added '[mybackup.remotehost.com]:22422,[172.16.0.100]:22422' (RSA) to the list of known hosts.
.tar: No such file or directory`

**Comment by ryanmboyce** [comment]
@gerard33 I just realized you didn't create that add-on so I submitted an Issue to the repository owner @carstenschroeder

**Comment by NixBiks** [comment]
Hi all,

I am sorry that I haven't been active at all. My situation is that I formed my own company and are very busy doing that. And I don't use `hassio` at this point anymore.

If there are anybody that wishes to maintain this then please let me know.

**Comment by overkill32** [comment]
@mr-bjerre I would like to take this over.  Please let me know how you'd like to proceed.

**Comment by NixBiks** [comment]
@overkill32 great! Now I don't have experience with that kind of process. I suppose something like [this](https://help.github.com/en/articles/transferring-a-repository)? Let me know if you have other suggestions.

**Comment by overkill32** [comment]
@mr-bjerre I also have not done a transfer before, but I agree that seems like the right instructions.

**Comment by esseki** [comment]
Hi,

@mr-bjerre or @overkill32 to fix the remote backup addon with the latest version of Home Assistant, you just need to add the following line

**"arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],**

in the "config.json".
You can have a look at what other addon maintainers have done to keep their addon up to date and working with the latest release of HA [https://github.com/carlosatta/hassio-addons/pull/16/commits/fbccbf97635b84f4f3a18197777dea61aff612eb](url)

FYI, this fixed the remote backup addon version 0.3.2 with my install of HASSOS running Home assistant 0.91.3 on an Arch64 based ODroid C2.

Hope this will help others ;)

**Comment by overkill32** [comment]
> @overkill32 great! Now I don't have experience with that kind of process. I suppose something like [this](https://help.github.com/en/articles/transferring-a-repository)? Let me know if you have other suggestions.

@mr-bjerre I'm ready when you are.  I think you have to initiate the transfer.

**Comment by NixBiks** [comment]
@overkill32 I should have initiated a transfer of this repo now together with [hassio-addons](https://github.com/mr-bjerre/hassio-addons). Feel free to keep me mentioned :)

**Comment by overkill32** [comment]
Repository transfer complete.  Will take me a bit to dig through backlog issues.   Open to input and PRs.

**Comment by gervaso** [comment]
Hello everyone, it's still broken because now the "config.json" points to the wrong url on the old repo. I suggest that you clone also the hassio-addons repo as well and update the documentation.

**Comment by gervaso** [comment]
I've created a pull request for the documentation update, you can also fork the repo I just fixed, hope it helps.

https://github.com/gervaso/hassio-addons

**Comment by overkill32** [comment]
#25

**Comment by catchdave** [comment]
@overkill32 : Looks like this issue has re-surfaced. I just tried to install it and got the below error:
```
 Can't install fixated/remote-backup-aarch64:0.3.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.3.2&fromImage=fixated%2Fremote-backup-aarch64: Not Found ("pull access denied for fixated/remote-backup-aarch64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied") 
 ```
