### ISSUE TITLE
Unable to pull from repository 

### ISSUE THREAD

**Issue by ryanmboyce** [mr-bjerre/hassio-remote-backup#22]
Getting following error when following instructions per Readme page, any ideas? This Add-On saved my ass when my RPI crashed and my backups were stored remotely. After restoring from backup this add-on doesn't work (uninstalled and re-installed) and getting the errors below now:

**404 Client Error: Not Found ("pull access denied for fixated/remote-backup-armv7, repository does not exist or may require 'docker login'**

`19-04-01 00:54:06 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/mr-bjerre/hassio-addons repository
19-04-01 00:54:07 INFO (MainThread) [hassio.addons] Load add-ons: 58 all - 1 new - 0 remove
19-04-01 00:54:27 INFO (SyncWorker_17) [hassio.docker.interface] Pull image fixated/remote-backup-armv7 tag 0.3.2.
19-04-01 00:54:29 ERROR (SyncWorker_17) [hassio.docker.interface] Can't install fixated/remote-backup-armv7:0.3.2 -> 404 Client Error: Not Found ("pull access denied for fixated/remote-backup-armv7, repository does not exist or may require 'docker login'").`

**Comment by yashijoe** [comment]
Here I got:

WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/ce20243c/remote-backup/config.json: required key not provided @ data['arch']. Got None

**Comment by overkill32** [comment]
#25

**Comment by javache** [comment]
This is still broken for me. Could it be that the `fixated/remote-backup` image is not published for armv7 (raspberry pi)? It doesn't show on dockerhub: https://hub.docker.com/search?q=fixated&type=image

**Comment by aschamberger** [comment]
Same here, it tries to download fixated/remote-backup-**armv7**:0.3.2 which is not present on dockerhub. armv7 architecture is however listed in the config.json here: https://github.com/overkill32/hassio-addons/blob/master/remote-backup/config.json
