### ISSUE TITLE
SSH key

### ISSUE THREAD

**Issue by gerard33** [mr-bjerre/hassio-remote-backup#3]
Is it also possible to use an authorized_key like in the [SSH addon](https://github.com/hassio-addons/addon-ssh#configuration) instead of the private key?

**Comment by NixBiks** [comment]
I don't see how that would be possible. You have to ssh INTO the remote server FROM hassio. That requires  a private key on the hassio and authorized key on remote. In ssh addon you ssh INTO hassio FROM some server. That requires authorized key on hassio and private on the from-server.

Correct me if I'm wrong.

**Comment by gerard33** [comment]
That's clear. I was just wondering if it was possible to avoid to have the private key visible in the config of the addon.
