### ISSUE TITLE
Impossible to setup - Load key "/root/.ssh/id": invalid format

### ISSUE THREAD

**Issue by septeven** [mr-bjerre/hassio-remote-backup#32]
Hello,
I spent litterrally the whole day trying to setup this with my NAS Synology but the readme is missing a lot of detailed informations for the non-high-qualified people to get it right.

I keep having the "Load key "/root/.ssh/id": invalid format" error which results in a "hassio_backup@192.168.xx.xx: Permission denied (publickey,password)" and "lost connection"

I have ssh-keygen through the SSH & Web terminal addon and have correctly put the public key into my .ssh/authorized_keys on my NAS. I have copy paste the private key (following the model shown on Readme, with double quotes and commas) in the Hassio-remote-backup config.

It sounds like this repo is not really kept updated though, I do hope someone will be able to help me on this.

Let me know if you need any other details
Thanks

**Comment by langestefan** [comment]
Hi, I have the same issue. Have you tried using the generated key pair PuTTY? My key pair fails on putty as well as on this addon so I am quite stuck now.

**Comment by septeven** [comment]
Hi,
After months, I'm trying to figure it out again this morning - how to make it working - but still the exact same problem, is there anyone still there ? @overkill32 @mr-bjerre
