### ISSUE TITLE
Confusion...

### ISSUE THREAD

**Issue by arretx** [mr-bjerre/hassio-remote-backup#7]
Not 100% sure how to go about creating the SSH key...

1.  I access my Ubuntu server through SSH from my MacBook.
2.  I access my Pi3 through SSH from my MacBook.
3.  Now I need to access my Ubuntu server from the Pi3.

What exactly is the ssh key that I'm looking for?

**Comment by NixBiks** [comment]
Hi arretx. This is not really related to this addon. What you need to do is

1. Log on to your Pi3 through SSH and run `ssh-keygen` which will generate a key pair.
1. Make the addon point to the private key.
1. Copy the public key to `.ssh\authorized_keys` on your Ubuntu machine.

Hope it makes sense. More info on ssh keys [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2)
